#%RAML 1.0 Trait
headers:
  client_id:
    description: The registered Client ID
    type: string
    required: true
    example: 1e5c95db5fc447aea20c07b161d3318e
  client_secret:
    description: The registered Client Secret
    type: string
    required: true
    example: b7e8205338D64A7680188e4E4498D596